### ISSUE TITLE
'colors' module dependency cannot be resolved

### ISSUE THREAD

**Issue by wiill** [Marak/play.js#5]
/usr/local/bin/node /Users/[hidden]/Dev/GitHub/MyRepo/play.js/examples/demo.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'colors'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/Users/[hidden]/Dev/GitHub/MyRepo/play.js/lib/play.js:37:16)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)

Process finished with exit code 1

Where to find? trying npm install colors doesn't work ('No Such Module' error)

**Comment by Marak** [comment]
Hrmm, thats odd!

Did you run `npm install` after you cloned your repo?

That should install the `colors` dep for you. You can also cd into your play.js directory and type `npm ls` to see if colors has installed correctly.

You can also try `npm install colors` in your play.js directory, or install colors globally with `npm install colors -g`

Please let me know!

**Comment by wiill** [comment]
Actually, I found out that I have issues with my PATH, and that npm has been installed in several places (/user/bin and /usr/local/bin)... so  calling the "right" bin for npm resolved my problem and could install properly colors dependency

Sorry for the trouble, don't blame the noob : )
in the end, I am not mastering my environment, though I can still develop and try on samples such as yours

So, btw, any links toward managing my NodeJS (and co) environment / PATH / bin location for noobs on MacOS X SL 10.6.8 ? (node_modules dir in my homedir, global (wtf that means?) install of modules, node_modules dir in project dir...)

Cheers!
